pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.9.9-amazoncorretto-17-alpine' }
      }
      steps {
        sh 'mvn --version'
      }
    }
  }
}